Repository syvita/daoos, pull requests merged in 2021-05, with the labels that each got.

#28 Add files via upload for architecture drawings
  docs/DAO-1.2-layer1.drawio
  docs/DAO-1.2-layer1.png
  docs/DAO-1.2-layer2.drawio
  docs/DAO-1.2-layer2.png
  docs/DAO-1.2-layer3.drawio
  docs/DAO-1.2-layer3.png
Labels: Drawio, PNG, documentation

#33 here is my take on it...does this make sense?
  docs/DAO-1.2-layer3.drew.xml
Labels: ⚠️ High Priority, ✏️ Diagram, ❓ Question

#27 Add first version of plugin-trait.
  packages/contracts/contracts/plugin-trait.clar
  packages/contracts/test/plugin-trait.ts
Labels: ⚠️ High Priority, 👀 Clarity, 💡 Feature
