Repository syvita/daoos, pull requests merged in 2021-06, with the labels that each got.

#20 Create LICENSE
  LICENSE
Labels: 🆘 Help Needed, 🌅 QOL, 💡 Feature, 📚 Docs, 🔅 Low Priority, 🧹 Chore

#37 Added typescript compiler github action, fixed prettier github action
  .github/workflows/lint.yml
  .github/workflows/tsc.yml
  .gitignore
  .prettierignore
  .prettierrc.json
  package-lock.json
  package.json
  packages/contracts/.prettierignore
  packages/contracts/.prettierrc.json
  packages/contracts/package-lock.json
  packages/contracts/package.json
  packages/contracts/test/counter.ts
  packages/ui/.prettierignore
  packages/ui/.prettierrc.json
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/pages/_app.js
  packages/ui/pages/api/hello.js
  packages/ui/pages/index.js
  tsconfig.json
Labels: ⚒️ CI/CD, ⚠️ High Priority, 🌅 QOL, 🧹 Chore

#19 Establishes linting for TypeScript in GH Actions
  .github/workflows/lint.yml
  .github/workflows/tsc.yml
  .gitignore
  .prettierignore
  .prettierrc.json
  package-lock.json
  package.json
  packages/contracts/.prettierignore
  packages/contracts/.prettierrc.json
  packages/contracts/package-lock.json
  packages/contracts/package.json
  packages/contracts/test/counter.ts
  packages/ui/.prettierignore
  packages/ui/.prettierrc.json
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/pages/_app.js
  packages/ui/pages/api/hello.js
  packages/ui/pages/index.js
  tsconfig.json
Labels: ⚒️ CI/CD, ✨ Next.js, 🌅 QOL, 👀 Clarity, 💡 Feature, 🧹 Chore

#52 Get Github actions to pass
  .prettierignore
  package-lock.json
  package.json
  packages/contracts/test/plugin-trait.ts
Labels: ⚒️ CI/CD, 🌅 QOL, 👀 Clarity, 🔅 Low Priority
